Upgrade to Micronaut 3.0.0-M2
micronaut-projects/micronaut-liquibase pull request #173
Opened 2021-06-21 12:10 UTC by ilopmar

2021-06-21 13:10 UTC, ilopmar commented
Of course all the test pass locally but fail on CI :sob:

2021-07-15 11:16 UTC, sdelamo requested changes

2021-07-15 11:16 UTC, sdelamo commented on liquibase/build.gradle
> +    api "io.projectreactor:reactor-core"
this should be `implementation` instead of `api`.

2021-07-15 11:28 UTC, sdelamo approved these changes

2021-07-16 07:53 UTC, merged

2021-07-16 09:00 UTC, graemerocher commented
Is there something specific this module needs that requires compiling against 3.0?

2021-07-16 09:09 UTC, ilopmar commented
No, it's not. But I think sooner or later we need to upgrade all modules to 3, so if this works without problems and we've already upgraded it, does it hurts to keep it?
I can rollback the change and compile against 2.5.9 if we want, it's not a problem at all :-)

2021-07-16 10:50 UTC, graemerocher commented
As discussed in the meeting every module that requires another downstream release adds to the work @jameskleeh is going to have to do to release everything 

It seems unnecessary to me to add to that work but it is up to @jameskleeh he is the one that will do the release

2021-07-16 11:38 UTC, ilopmar commented
Yes, you are right. I can rollback to 2.5.9.