build: Move to using our latest build infrastructure
micronaut-projects/micronaut-liquibase pull request #262
Opened 2022-04-20 18:17 UTC by wetted

This moves to using managed versions and a library catalog, this means that we get the managed liquibase version in our catalog toml file exported by the bom.

This is the only change, no other dependencies have changed, so I believe this can go out as a patch release.

Fixes #261

2022-04-21 14:43 UTC, timyates requested changes

2022-04-21 14:43 UTC, timyates commented on gradle.properties
> -micronautDocsVersion=2.0.0
The micronaut docs annotation processor is injected automagically by the common plugin I think.

So we need this here (as the plugin uses it for the version)

However we can remove both `micronaut-docs = "2.0.0"` and the `micronaut-docs = {` line from `libs.versions.toml`

And then we can remove the `annotationProcessor libs.micronaut.docs` from `liquibase/build.gradle`

2022-04-21 17:54 UTC, timyates approved these changes
inject-java annotation processor is injected automatically, I pushed a commit that removes it

Not sure if we need inject-java at all

I assume it's there for a reason I can't see though 👍

2022-04-28 09:32 UTC, sdelamo approved these changes

2022-04-28 09:33 UTC, merged